sms.homepage:
    path:     /smsapi/test
    defaults: { _controller: TMSolutionSmsBundle:Default:test }
    
sms.smsapi.callback:
    path:     /smsapi/test
    defaults: { _controller: TMSolutionSmsBundle:Default:callback }
